### ISSUE TITLE
Cross-overs of gate circuits

### ISSUE THREAD

**Issue by komal-kk** [rsehgal/barcQ#92] opened 2020-12-14 05:23 UTC
1) control bits on bit 0, 2, and target bit 1
2) control bits on bit 1, 4, and target bit on 2.
These examples where the target bit comes in between of the control bits require crossing over of certain gates by CNOT. I'm trying that but I'm not sure if that is possible in the portal.  For example, in the 2nd case, at one point the CNOT gate will cross the Hadamard gate as: CNOT - control bit 1, target bit 4 and Hadamard on bit 2. Please check.
![image](https://user-images.githubusercontent.com/72011872/102041891-9e2e0f80-3df6-11eb-96f4-5ed64f3b2c59.png)

_Originally posted by @komal-kk in https://github.com/rsehgal/barcQ/issues/88#issuecomment-744165130_

**Comment by komal-kk** [comment] 2020-12-14 07:02
Issue resolved:

![image](https://user-images.githubusercontent.com/72011872/102050165-4d271700-3e08-11eb-98d6-5fff060b9556.png)

![image](https://user-images.githubusercontent.com/72011872/102050194-5a440600-3e08-11eb-89c7-b1ec63eeb29a.png)
 Corresponding Toffoli gate:

![image](https://user-images.githubusercontent.com/72011872/102050233-6b8d1280-3e08-11eb-8406-a4fcbd74da7e.png)

![image](https://user-images.githubusercontent.com/72011872/102050246-721b8a00-3e08-11eb-8376-f37d3cca54ea.png)

**Comment by komal-kk** [comment] 2020-12-14 07:03
Instead of crossover, the Hadamard gate was shifted to the right of the CNOT gate it was crossing.

**Comment by rsehgal** [comment] 2020-12-14 07:49
Thanks @komal-kk,
Since the issue is resolved, hence closing it.

**Closed by rsehgal** 2020-12-14 07:49 UTC
